"""
Django settings for crud project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q%jlx7i*)+m%*mvmj7=ld&p4nzf(e-&*t*hm&+(%y_eqjugch&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# SITE_ID = 1

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'django_apscheduler',
    'rest_framework',
    'geocoding.apps.GeocodingConfig',
    # 'corsheaders',
    'operation.apps.OperationConfig',
#    'django.contrib.sites',
#     'allauth',
#     'allauth.account',
#     'allauth.socialaccount',
#     'allauth.socialaccount.providers.google' 
]


# SOCIALACCOUNT_PROVIDERS = {
#     'google':{
#        'SCOPE' : [
#            "profile",
#            "email"
#         ],
#         'AUTH_PARAMS' : {"access_type" : "online"}
#     }    
# }

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.accounts.auth_backends.AuthenticationBackend'
# )


APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Default

SCHEDULER_DEFAULT = True

APPEND_SLASH = False


import os
from dotenv import load_dotenv
load_dotenv()
MAIL_USERNAME = os.getenv('MAIL_USERNAME')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = MAIL_USERNAME
EMAIL_HOST_PASSWORD = MAIL_PASSWORD

# CACHE_KEY_WARNS = False

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "TIMEOUT" : 60*10
    }
}

# CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'operation.middleware.JWTMiddleware'
]

ROOT_URLCONF = 'crud.urls'

TEMPLATES = [
    # {
    #     'BACKEND': 'django.template.backends.django.DjangoTemplates',
    #     'DIRS': [],
    #     'APP_DIRS': True,
    #     'OPTIONS': {
    #         'context_processors': [
    #             'django.template.context_processors.debug',
    #             'django.template.context_processors.request',
    #             'django.contrib.auth.context_processors.auth',
    #             'django.contrib.messages.context_processors.messages',
    #         ],
    #     },
    # },
]

WSGI_APPLICATION = 'crud.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
import pymysql
pymysql.install_as_MySQLdb

# GDAL_LIBRARY_PATH = '/usr/share/gdal'


DATABASES = {
    'default':{

    },
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',  
        'NAME': 'DjangoCrud',  
        'USER':'root',  
        'PASSWORD':'password',  
        'HOST':'localhost',  
        'PORT':'3306' 
    },
    'slave': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',  
        'NAME': 'DjangoCrud',  
        'USER':'root',  
        'PASSWORD':'password',  
        'HOST':'localhost',  
        'PORT':'3306' 
    },
     'mongodb': {
        'ENGINE': 'djongo',
        'NAME': 'DjangoTask',
        # 'CLIENT': {
        #     'host': 'mongodb://localhost:27017',
        # }
        'HOST':'localhost',
        'PORT':27017
    }
}

DATABASE_ROUTERS = ['db_router.router.MasterSlaveRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
